### GET Request All Recipes
GET http://localhost:3000/recipes

### GET Request All Ingredients
GET http://localhost:3000/ingredients

### GET Request All Nutrition
GET http://localhost:3000/nutrition

### GET Request Single Recipe by ID
GET http://localhost:3000/recipes/6740f33444fafe77814e3a84

### GET Request Single Ingredient by ID
GET http://localhost:3000/ingredients/

### GET Request Single Nutrition by ID
GET http://localhost:3000/nutrition/

### POST Create New Recipe
POST http://localhost:3000/recipes HTTP/1.1
Content-Type: application/json

{
  "title": "Shredded BBQ Pork" ,
  "description": "Dairy-Free, Diabetic, Gluten-Free, Ketogenic, Lower Sodium",
  "cooking_time": "6-8",
  "servings": 8,
  "materials": "1 gallon-sized freezer bag",
  "instructions": {
    "to_freeze_and_cook_later": [
      "1. Label your freezer bag with the name of the recipe, cooking instructions, and 'use-by' date.",
      "2. Add all ingredients to your freezer bag.",
      "3. Remove as much air as possible, seal, and freeze."
    ],
    "to_cook": [
      "1. Thaw freezer bag overnight in refrigerator or in water in the morning.",
      "2. Pour contents of freezer bag into your crockpot.",
      "3. Cook on 'low' setting for 6-8 hours.",
      "4. Shred pork and stir."
    ]
  }
}

### POST Create New Ingredient
POST http://localhost:3000/ingredients HTTP/1.1
Content-Type: application/json

{
   "ingredient_name": "boneless pork roast",
   "ingredient_quantity": "2",
   "ingredient_unit": "lb",
   "recipe_id": "6740ed98d64cd6e43df1d"
}

### POST Create New Nutrition
POST http://localhost:3000/nutrition HTTP/1.1
Content-Type: application/json

{
        "calories": "193",
        "calories_unit": "kcal",
        "polyunsaturated_fat": "1",
        "polyunsaturated_fat_unit": "g",
        "potassium": "572",
        "potassium_unit": "mg",       
        "carbohydrates": "11",
        "carbohydrates_unit": "g",
        "monounsaturated_fat": "2",
        "monounsaturated_fat_unit": "g",
        "fiber": "1",
        "fiber_unit": "g",
        "protein": "26",
        "protein_unit": "g",
        "fat": "5",
        "fat_unit": "g",
        "recipe_id": "6740ed98d64cd6e43df1d24a"
}

### PUT Update Recipe by ID
PUT http://localhost:3000/recipes/6740f33444fafe77814e3a84 HTTP/1.1
Content-Type: application/json

{
    "title": "Shredded Pork",
    "description": "Dairy-Free, Diabetic, Gluten-Free, Ketogenic, Lower Sodium",
    "cooking_time": "6-8",
    "servings": "8",
    "materials": "1 gallon-sized freezer bag",
    "instructions": {        
        "to_freeze_and_cook_later": [
            "1. Label your freezer bag with the name of the recipe, cooking instructions, and 'use-by' date.",
            "2. Add all ingredients to your freezer bag.",
            "3. Remove as much air as possible, seal, and freeze."
            ],
        "to_cook": [
            "1. Thaw freezer bag overnight in refrigerator or in water in the morning.",
            "2. Pour contents of freezer bag into your crockpot.",
            "3. Cook on 'low' setting for 6-8 hours.",
            "4. Shred pork and stir."
        ]
    }
}

### PUT Update Ingredient by ID
PUT http://localhost:3000/ingredients/67422b1f61ef6ad1f50ebbb4 HTTP/1.1
Content-Type: application/json

{
   "ingredient_name": "boneless pork roast",
   "ingredient_quantity": "2",
   "ingredient_unit": "lb",
   "recipe_id": "6740ed98d64cd6e43df1d24a"
}

### DELETE Recipe By ID
DELETE http://localhost:3000/recipes/674156956674c217b0416bcc

### DELETE Ingredient By ID
DELETE http://localhost:3000/ingredients/67422b1f61ef6ad1f50ebbb4